language: python

# sudo false implies containerized builds
sudo: false

python:
  - 2.7
  - 3.6

before_install:
    - echo "Setup goes here"
install:
    - echo "Install goes here"
script:
    - echo "Tests go here"

