language: python

# sudo false implies containerized builds
sudo: false

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

python:
  - 3.6

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver

    - pip install -U requests \
                    selenium \
                    beautifulsoup4 \
                    oauth2client \
                    gspread \
                    coloredlogs \
                    pytest
install:
    - python setup.py install
script:
    - pytest

