language: python

# sudo false implies containerized builds
sudo: false

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

python:
  - 3.6

before_install:
    - pip install -U requests \
                    selenium \
                    beautifulsoup4 \
                    oauth2client \
                    gspread \
                    coloredlogs
install:
    - python setup.py install
script:
    - echo "Tests go here"

